services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: C.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  worker:
    build: .
    command: celery -A monitoria worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
    env_file:
      - .env

  beat:
    build: .
    command: celery -A monitoria beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
