services:
  - type: web
    name: monitoria-web
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: sua_chave_segura_aqui
      - key: DATABASE_URL
        fromDatabase:
          name: monitoria-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: monitoria-redis
          type: redis

  - type: web
    name: monitoria-worker
    env: docker
    plan: free
    autoDeploy: false
    startCommand: celery -A monitoria worker --loglevel=info & python worker_dummy_server.py

databases:
  - name: monitoria-db

  - name: monitoria-redis
    type: redis
