# Generated by Django 5.2.1 on 2025-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='frequencia_minutos',
            field=models.IntegerField(default=60),
        ),
    ]
