# Generated by Django 5.2.1 on 2025-05-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_url_frequencia_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='frequencia_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
