# Generated by Django 5.2.1 on 2025-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_url_frequencia_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='dias_da_semana',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='url',
            name='receber_notificacoes',
            field=models.BooleanField(default=False),
        ),
    ]
